//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIRDS
    {
        public int ID_Birds { get; set; }
        public string BirdName { get; set; }
        public Nullable<int> BirdAge { get; set; }
        public string BirdColor { get; set; }
        public string BirdType { get; set; }
        public int Typey_ID { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
