//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyMoments
    {
        public int ID_BuyMomnets { get; set; }
        public int Food_ID { get; set; }
        public int Tools_ID { get; set; }
        public int LivePointsForWorkers_ID { get; set; }
        public int Animals_ID { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual FOOD FOOD { get; set; }
        public virtual LivePointsForWorkers LivePointsForWorkers { get; set; }
        public virtual TOOLS TOOLS { get; set; }
    }
}
