//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class FROGS
    {
        public int ID_Frogs { get; set; }
        public string FrogName { get; set; }
        public Nullable<int> FrogAge { get; set; }
        public string FrogColor { get; set; }
        public string FrogType { get; set; }
        public int Typey_ID { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
