//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARGHEntities : DbContext
    {
        public ARGHEntities()
            : base("name=ARGHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<BIRDS> BIRDS { get; set; }
        public virtual DbSet<BuyMoments> BuyMoments { get; set; }
        public virtual DbSet<CATS> CATS { get; set; }
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<DOGS> DOGS { get; set; }
        public virtual DbSet<FOOD> FOOD { get; set; }
        public virtual DbSet<FROGS> FROGS { get; set; }
        public virtual DbSet<LivePointsForWorkers> LivePointsForWorkers { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Points> Points { get; set; }
        public virtual DbSet<RATS> RATS { get; set; }
        public virtual DbSet<TOOLS> TOOLS { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
