//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID_Orders { get; set; }
        public string OrderData { get; set; }
        public Nullable<int> HowManyAnimals { get; set; }
        public string TypeOfAnimal { get; set; }
        public string SterilizationOrCastrationNeed { get; set; }
        public int Client_ID { get; set; }
        public int Points_ID { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual Points Points { get; set; }
    }
}
