//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workers
    {
        public int ID_Workers { get; set; }
        public string WorkName { get; set; }
        public string WorkSureName { get; set; }
        public string WorkMiddleName { get; set; }
        public string WorkMail { get; set; }
        public int WorkLivePoint_ID { get; set; }
        public int Points_ID { get; set; }
    
        public virtual LivePointsForWorkers LivePointsForWorkers { get; set; }
        public virtual Points Points { get; set; }
    }
}
